apiVersion: v1
kind: Service
metadata:
  name: kratia-centralized
spec:
  type: NodePort
  ports:
    - name: kratia-centralized
      port: 8080
      targetPort: 8080
  selector:
    app: kratia-centralized