apiVersion: v1
kind: Service
metadata:
  name: kratia-centralized
spec:
  type: NodePort
  ports:
    - name: kratia-centralized
      port: 9000
      targetPort: 9000
  selector:
    app: kratia-centralized